### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by Macci2008** [knowhy/py-hue-influxdb#1]
I get the following issue when starting the script

Traceback (most recent call last):
  File "hue-sensors.py", line 90, in <module>
    update_data()
  File "hue-sensors.py", line 33, in update_data
    for key in j.items():
AttributeError: 'list' object has no attribute 'items'

**Comment by knowhy** [comment]
Puh ... Haven't looked at this project in a while. Have you checked if 

`curl http://hue_host/api/hue_user/sensors`

returns something? I wrote this against the v1 hue api which has been deprecated by now. I haven't checked if the newer hue models use a different api.

**Comment by Macci2008** [comment]
no worries...just playing around with an old Raspberry PI and new to that stuff.
executing that statement the feedback  looks OK ( I provide only an excerpt):

{"1":{"state":{"daylight":true,"lastupdated":"2021-01-04T07:42:00"},"config":{"on":true,"configured":true,"sunriseoffset":30,"sunsetoffset":-30},"name":"Daylight","type":"Daylight","modelid":"PHDL00","manufacturername":"Signify Netherlands B.V.","swversion":"1.0"},"2":{"state":{"buttonevent":4002,"lastupdated":"2021-01-04T07:17:35"},"swupdate":{"state":"noupdates","lastinstall":"2019-10-08T17:10:41"},"config":{"on":true,"battery":92,"reachable":true,"pending":[]},"name":"Wohnzimmer Dimmer","type":"ZLLSwitch",....

**Comment by Macci2008** [comment]
found the issue - created a new hue user and tried it with that one - seem to work now
